name: 'SaaStack Variable Substitution'
description: 'Verifies and Substitutes all settings in files like `appsettings.json` with variables/secrets defined in the GitHub repository'
inputs:
  files:
    description: 'A comma-delimited list of glob patterns that identify all the `appsettings.json` files to be processed, relative to the root of the repository'
    required: true
    default: '**/appsettings.json'
  secrets:
    description: 'The secrets of the GitHub repository. Must be the value: \$\{\{ toJSON(secrets)\}\}'
    required: true
  variables:
    description: 'The variables of the GitHub repository (and environment). Must be the value: \$\{\{ toJSON(vars)\}\}'
    required: true
  warnOnAdditionalVars:
    description: 'Whether to output warnings if there are additional variables or secrets in the GitHub repository that are not substituted into any files'
    required: false
    default: false
  ignoreAdditionalVars:
    description: 'A regular expression that matches any GitHub variables/secrets that should be ignored if `warnOnAdditionalVars` is enabled'
    required: false
runs:
  using: 'node20'
  main: './built/index.js'
